#!/bin/bash

# Clean old files out of the CollectionSpace temp directory.

if [[ -z $CS_TEMP_MMIN ]]; then
	CS_TEMP_MMIN=60 # Minimum minutes since last modification required for a file to be deleted
fi

TEMP_DIR=~/`~/bin/csservname`/temp
COUNT=0

cd "$TEMP_DIR"

echo "`date`: Cleaning `pwd`"

while read dir
do
	echo "Removing $dir"

	/bin/rm -rf "$dir"

	if [[ -d $dir ]]; then
		echo "ERROR: Failed to remove $dir"
	else
		COUNT=$((COUNT+1))
	fi
done < <(find . -maxdepth 1 -type d -name '*-*-*-*-*' -mmin +${CS_TEMP_MMIN})

echo "Removed $COUNT directories from `pwd`"
