#!/bin/bash

# Clean old files out of the CollectionSpace temp directory.

if [[ -z $CS_TEMP_MMIN ]]; then
	CS_TEMP_MMIN=60 # Minimum minutes since last modification required for a file to be deleted
fi

TEMP_DIR=~/`~/bin/csservname`/temp

cd "$TEMP_DIR"

echo "`date`: Cleaning `pwd`"

DIR_COUNT=0

while read dir
do
	echo "Removing $dir"

	/bin/rm -rf "$dir"

	if [[ -d $dir ]]; then
		echo "ERROR: Failed to remove $dir"
	else
		DIR_COUNT=$((DIR_COUNT+1))
	fi
done < <(find . -maxdepth 1 -type d -name '*-*-*-*-*' -mmin +${CS_TEMP_MMIN})

echo "Removed $DIR_COUNT directories from `pwd`"

FILE_COUNT=0

while read file
do
	echo "Removing $file"

	/bin/rm "$file"

	if [[ -f $file ]]; then
		echo "ERROR: Failed to remove $file"
	else
		FILE_COUNT=$((FILE_COUNT+1))
	fi
done < <(find . -maxdepth 1 -type f -name '*.tmp' -o -name '*.xml' -o -name '*.properties' -mmin +${CS_TEMP_MMIN})

echo "Removed $FILE_COUNT files from `pwd`"
