#!/bin/bash

TEMP_DIR=~/`csname`/temp
MMIN=60
COUNT=0

cd "$TEMP_DIR"

echo "Cleaning `pwd`"

while read dir
do
	echo "Removing $dir"

	/bin/rm -rf "$dir"

	if [[ -d $dir ]]; then
		echo "ERROR: Failed to remove $dir"
	else
		COUNT=$((COUNT+1))
	fi
done < <(find . -maxdepth 1 -type d -name '*-*-*-*-*' -mmin +${MMIN})

echo "Removed $COUNT directories from `pwd`"
