#!/bin/bash

# Print the time the CollectionSpace tomcat service was started.

SERVICE_NAME=`csservname`
PID=`pgrep -fn -u $USER "java .* -Dcatalina.base=/home/$USER/$SERVICE_NAME "`

if [ -n "$PID" ]; then
	START_TIME=`ps -o lstart= -p $PID`
	date -d "$START_TIME" "$@"
fi
