./load-report.sh ArcheologicalSiteReport  "Archaeological Inventory" ""
./load-report.sh AudioRecording  "Audio recordings by artist" ""
./load-report.sh BriefObjectSummary  "Brief object summary" ""
./load-report.sh CatalogCard  "Catalog card report" ""
./load-report.sh DetailedObject  "Detailed object summary" ""
./load-report.sh groupObject  "Basic Group Report" ""
./load-report.sh Inventory  "Inventory Report" ""
./load-report.sh KeyInformationReview  "Key Information Review" ""
./load-report.sh NAGPRA  "NAGPRA report" ""
./load-report.sh PackingList  "Packing List Report" ""
./load-report.sh PlaceReport  "Place Report" ""
./load-report.sh Rehousing  "Rehousing report" ""
./load-report.sh ResearcherSummary  "Researcher summary" ""
./load-report.sh SingleObjectSummary  "Basic Object Report" ""
