UPDATE propagations_common SET planttype= 'urn:cspace:botgarden.cspace.berkeley.edu:vocabularies:name(propPlantType):item:name(bareRoot)''bare root''' WHERE proptype = 'bare root';
UPDATE propagations_common SET planttype= 'urn:cspace:botgarden.cspace.berkeley.edu:vocabularies:name(propPlantType):item:name(bulb)''bulb''' WHERE proptype = 'bulb';
UPDATE propagations_common SET planttype= 'urn:cspace:botgarden.cspace.berkeley.edu:vocabularies:name(propPlantType):item:name(bulbScales)''bulb scales''' WHERE proptype = 'bulb scales';
UPDATE propagations_common SET planttype= 'urn:cspace:botgarden.cspace.berkeley.edu:vocabularies:name(propPlantType):item:name(bulblets)''bulblets''' WHERE  proptype = 'bulblets';
UPDATE propagations_common SET planttype= 'urn:cspace:botgarden.cspace.berkeley.edu:vocabularies:name(propPlantType):item:name(bulbs)''bulbs''' WHERE  proptype = 'bulbs';
UPDATE propagations_common SET planttype= 'urn:cspace:botgarden.cspace.berkeley.edu:vocabularies:name(propPlantType):item:name(corm)''corm''' WHERE  proptype = 'corm';
UPDATE propagations_common SET planttype= 'urn:cspace:botgarden.cspace.berkeley.edu:vocabularies:name(propPlantType):item:name(corms)''corms''' WHERE  proptype = 'corms';
UPDATE propagations_common SET planttype= 'urn:cspace:botgarden.cspace.berkeley.edu:vocabularies:name(propPlantType):item:name(division)''division''' WHERE  proptype = 'division';
UPDATE propagations_common SET planttype= 'urn:cspace:botgarden.cspace.berkeley.edu:vocabularies:name(propPlantType):item:name(livingPlant)''living plant''' WHERE  proptype = 'living plant';
UPDATE propagations_common SET planttype= 'urn:cspace:botgarden.cspace.berkeley.edu:vocabularies:name(propPlantType):item:name(rootedPieces)''rooted pieces''' WHERE  proptype = 'rooted pieces';
UPDATE propagations_common SET planttype= 'urn:cspace:botgarden.cspace.berkeley.edu:vocabularies:name(propPlantType):item:name(seedling)''seedling''' WHERE  proptype = 'seedling';
UPDATE propagations_common SET planttype= 'urn:cspace:botgarden.cspace.berkeley.edu:vocabularies:name(propPlantType):item:name(seedlings)''seedlings''' WHERE  proptype = 'seedlings';
UPDATE propagations_common SET planttype= 'urn:cspace:botgarden.cspace.berkeley.edu:vocabularies:name(propPlantType):item:name(transplant)''transplant''' WHERE  proptype = 'transplant';
UPDATE propagations_common SET planttype= 'urn:cspace:botgarden.cspace.berkeley.edu:vocabularies:name(propPlantType):item:name(tuber)''tuber''' WHERE  proptype = 'tuber';
