curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Ball%20Room_Full.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Ball%20Room_Thumb.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Billiard%20Room_Full.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Billiard%20Room_Thumb.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/CandleStick_Full.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/CandleStick_Thumb.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Cluedo.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Cluedo.mp    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Cluedo_Small.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Cluedo_Smaller.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Cluedo_Smaller2.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Col%20Mustard_Full.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Col%20Mustard_Thumb.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Conservatory_Full.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Conservatory_Thumb.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Dagger_Full.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Dagger_Thumb.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Dining%20Room_Full.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Dining%20Room_Thumb.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Hall_Full.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Hall_Thumb.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Kitchen_Full.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Kitchen_Thumb.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Lead%20Piping_Full.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Lead%20Piping_Thumb.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Library_Full.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Library_Thumb.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Lounge_Full.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Lounge_Thumb.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Miss%20Scarlet_Full.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Miss%20Scarlet_Thumb.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Miss%20Scarlet_old.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Miss%20White_Full.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Miss%20White_Thumb.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Mrs%20Peacock_Full.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Mrs%20Peacock_Thumb.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Mrs%20Peacock_old.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Mrs%20White_old.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Prof%20Plum_Full.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Prof%20Plum_Thumb.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Professor%20Plumb_old.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Rev%20Green_Full.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Rev%20Green_Thumb.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Revolver_Full.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Revolver_Thumb.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Rope_Full.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Rope_Thumb.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Spanner_Full.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Spanner_Thumb.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Study_Full.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Study_Thumb.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/Thumbs.db    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/cluedo%20board_00.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/cluedo%20board_01.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/cluedo%20board_smear.jpg    
curl -O  http://www.quizmasters.biz/Pub%20Genius/Cluedo/Gfx/cluedo-original3.jpg    
